#!/bin/bash
echo "Content-type: text/plain"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')

curl -X POST "http://10.0.0.229:5001/api/v0/block/get?arg=$arg"

# arg [string]: The CID of an existing block to get. Required: yes.
