#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')
eval $(echo "$url" | awk -F'[=&?]' '{print $4}')=$(echo "$url" | awk -F'[=&?]' '{print $5}')
eval $(echo "$url" | awk -F'[=&?]' '{print $6}')=$(echo "$url" | awk -F'[=&?]' '{print $7}')

curl -X POST "http://10.0.0.229:5001/api/v0/block/rm?arg=$arg&force=$force&quiet=$quiet"

# arg [string]: CIDs of block(s) to remove. Required: yes.
# force [bool]: Ignore nonexistent blocks. Required: no.
# quiet [bool]: Write minimal output. Required: no.
