#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')
eval $(echo "$url" | awk -F'[=&?]' '{print $4}')=$(echo "$url" | awk -F'[=&?]' '{print $5}')

curl -X POST "http://10.0.0.229:5001/api/v0/bootstrap/add?arg=$arg&default=$default"

# arg [string]: A peer to add to the bootstrap list (in the format '<multiaddr>/<peerID>') Required: no.
# default [bool]: Add default bootstrap nodes. (Deprecated, use 'default' subcommand instead). Required: no.

# BUG: doesn't work?
