#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')

curl -X POST "http://10.0.0.229:5001/api/v0/bitswap/ledger?arg=$arg"

# arg [string]: The PeerID (B58) of the ledger to inspect. Required: yes.
