#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')

if [ ! -z $peer ]; then peer_="peer=$peer"; fi

curl -X POST "http://10.0.0.229:5001/api/v0/bitswap/wantlist?$peer_"

# peer [string]: Specify which peer to show wantlist for. Required: no.

# BUG IN docs: peer is required; without it = "failed to parse peer ID: invalid cid: cid too short"
