#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')
eval $(echo "$url" | awk -F'[=&?]' '{print $4}')=$(echo "$url" | awk -F'[=&?]' '{print $5}')

curl -X POST "http://10.0.0.229:5001/api/v0/cid/bases?prefix=$prefix&numeric=$numeric"

# prefix [bool]: also include the single letter prefixes in addition to the code. Required: no.
# numeric [bool]: also include numeric codes. Required: no.
