#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')

curl -X POST "http://10.0.0.229:5001/api/v0/cid/base32?arg=$arg"

# arg [string]: CIDs to convert. Required: yes.
