#!/bin/bash
echo "Content-type: application/json"
echo
url="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/ipfswna?url=//g")"
# /etc/hosts looks something like 127.0.0.1 a.lan \ 10.0.0.233 b.lan
localip="b.lan"
basepath="/zd/put/cunt/cid"
urlsafe=$(echo "$url" | sed "s/:\|\/\|?\|=\|&\|(\|)\|,\|@\|+\|*\|%\|#/-/g")
curl -sLk "$url" | ffmpeg -i pipe:0 -c:v copy -an -f webm pipe:1 | curl -k -X POST -F file="@-;filename=rmaudio.$urlsafe" "https://$localip:5001/api/v0/add?cid-version=1&chunker=size-1048576&recursive=true&wrap-with-directory=true&pin=false" | tee -a "$basepath/cids$(TZ=UTC date -u +%Y%m%d).txt"
