#!/bin/bash
echo "Content-type: application/json"
echo
url="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/ipfs0?url=//g")"
localip="10.0.0.232"
basepath="/zd/put/cunt/cid"

# urlsafe is POINTLESS because /api/v0/add has no stdin-name thing
# update: use file=@-;filename= instead
urlsafe=$(echo "$url" | sed "s/:\|\/\|?\|=\|&\|(\|)\|,\|@\|+\|*\|%\|#/-/g")
curl -sLk "$url" | curl -k -X POST -F file="@-;filename=$urlsafe" "https://$localip:5001/api/v0/add?cid-version=1&chunker=size-1048576&recursive=true&wrap-with-directory=true&pin=false" | tee -a "$basepath/cids$(TZ=UTC date -u +%Y%m%d).txt"
