#!/bin/bash
echo "Content-type: text/plain"
echo
localip="10.0.0.232"
pidcount=$(ps -ef | grep -v grep | grep "mem " | wc -l)
if [ $pidcount -gt 5 ]; then
    echo "Too many arc PID(s) detected. Try again later. PID(s):"
    ps -ef | grep -v grep | grep "mem " | grep -n $
    exit 0
else
    url="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/mem?url=//g")"
    basepath="/zc/put/cunt/warc"
    time="$(TZ=UTC date -u +%Y%m%d%H%M%S)"
    timeu=$(date +%s)
    urlsafe=$(echo "$url" | sed "s/:\|\/\|?\|=\|&\|(\|)\|,\|@\|+\|*\|%\|#/-/g")
    urllen=$(echo -n $time-$urlsafe | wc --bytes)
    if [ $urllen -gt 200 ]; then
        urlsafe="$(echo $urlsafe | perl -pE "s/^(.{200}).*/\1.URL2LONG/g")"
    fi

    echo -n "url is: "; echo "$url" | tee $basepath/$time-$urlsafe.txt
    echo "urlsafe: $urlsafe"
    echo "time is: $time, $timeu"; echo

    echo "Main CID at the bottom:"
    cd $basepath; TZ=UTC wget --no-check-certificate -p --span-hosts --adjust-extension --convert-links --restrict-file-names=windows --warc-max-size=99123456 --warc-cdx -e robots=off --warc-file=$basepath/$time-$urlsafe --directory-prefix=$basepath/../memento/$timeu/memento/$time/ "$url" 2>/dev/null
    urlpath=$(echo $url | sed "s/^https\?:\/\///g")
    mv -n "$basepath/../memento/$timeu/memento/$time/${urlpath}.html" "$basepath/../memento/$timeu/memento/$time/${urlpath}"
    filesf() { basedir="$basepath/../memento/$timeu"; basedirlen=$(expr $(echo -n "$basedir" | wc --bytes) + 1); find "$basedir" -type f | basedirlen="$basedirlen" xargs -d "\n" sh -c 'for args do nobasedir=$(echo "$args" | sed -E "s/^.{$basedirlen}//g"); echo " -F "file=@"\"$args\";filename=\"$nobasedir\"" | tr -d \\n; done' _; }
    curl -k -X POST -H "Content-Type: multipart/form-data" $(filesf) "https://$localip:5001/api/v0/add?cid-version=1&chunker=size-1048576&recursive=true&wrap-with-directory=true&pin=false"
fi
