#!/bin/bash
echo "Content-type: text/plain"
echo
localip="10.0.0.232"
id="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/resh?id=//g")"
curl -sLk "https://$localip/cgi-bin/ipfsapi/v0/resolve?arg=$id" | jq .Path | sed "s/\"//g" | sed "s/^\/ipfs\///g"
