#!/bin/bash
echo "Content-type: text/plain"
echo
localip="10.0.0.232"
id="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/tailph?id=//g")"
curl -sLk "https://$localip/cgi-bin/tail?url=https://$localip/cgi-bin/ipfsapi/v0/routing/provide?arg=$id"
