#!/bin/bash
echo "Content-type: text/plain"
echo
localip="10.0.0.232"
id="$(curl -sLk https://$localip/cgi-bin/resm?id=$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/tailpm?id=//g"))"
curl -sLk "https://$localip/cgi-bin/tail?url=https://$localip/cgi-bin/ipfsapi/v0_edit_mpc/routing/provide?arg=$id"
