#!/bin/bash
echo "Content-type: text/plain"
echo
# /etc/hosts looks something like 127.0.0.1 a.lan \ 10.0.0.233 b.lan
localip="b.lan"
id="$(curl -sLk https://$localip/cgi-bin/resh?id=$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/tailph?id=//g"))"
curl -sLk "https://$localip/cgi-bin/tailtext?url=https://$localip/cgi-bin/ipfsapi/v0/routing/provide?arg=$id"
