#!/bin/bash
echo "Content-type: application/json"
echo
url="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/test?url=//g")"

#0? (not echo "$url")
#echo $url

#1
#echo ==pwd:
#pwd
# result of
# $ curl -sLk 'https://10.0.0.200/cgi-bin/test?url=;pwd'
# --->
# ;pwd
# ==pwd:
# /usr/lib/cgi-bin

#2
#curl -sk --max-redirs 0 --max-time 30 "$url"

#3
echo "URL: $url"
echo "$REQUEST_URI"
echo $REMOTE_ADDR
echo "$SERVER_NAME"
echo $HTTPS
