#!/bin/bash
echo "Content-type: text/plain"
echo
basepath="/zd/put/cunt/selenium"
echo > "$basepath/run1"
echo "Disabled"

#--fails
#process = subprocess.Popen(['python3', '-c', 'from selenium import webdriver;options=webdriver.ChromeOptions();options.binary_location=\"/usr/bin/brave-browser\";driver=webdriver.Chrome(options=options);driver.get(\"https://chat-gpt.org/chat\");'], stdout=subprocess.PIPE);
#output, error = process.communicate();
#print(output.decode());

#print("webserver test");

#form = cgi.FieldStorage()
#url = form.getvalue('url')
#print(url)
