#!/bin/bash
echo "Content-type: text/plain"
echo
echo > /zc/put/cunt/selenium/run1
echo "Disabled"

#!/usr/bin/env bash
#import cgi
#import subprocess
#import datetime
#import subprocess
#from selenium import webdriver
#import selenium
#print("Content-type: text/plain");
#print();

#--fails
#process = subprocess.Popen(['python3', 'selenium.py'], stdout=subprocess.PIPE);
#output, error = process.communicate();
#print(output.decode());

#--fails
#process = subprocess.Popen(['python3', '-c', 'from selenium import webdriver;options=webdriver.ChromeOptions();options.binary_location=\"/usr/bin/brave-browser\";driver=webdriver.Chrome(options=options);driver.get(\"https://chat-gpt.org/chat\");'], stdout=subprocess.PIPE);
#output, error = process.communicate();
#print(output.decode());

#print("webserver test");

#form = cgi.FieldStorage()
#url = form.getvalue('url')
#print(url)
