#!/bin/bash
echo "Content-type: text/plain"
echo
url="$(echo -n "$REQUEST_URI" | sed "s/^\/cgi-bin\/urlon?url=//g")"
echo "Yes do it" > /zc/put/cunt/selenium/run1
echo "$url" > /zc/put/cunt/selenium/run2
echo "URL: $url"
