#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')
eval $(echo "$url" | awk -F'[=&?]' '{print $4}')=$(echo "$url" | awk -F'[=&?]' '{print $5}')
eval $(echo "$url" | awk -F'[=&?]' '{print $6}')=$(echo "$url" | awk -F'[=&?]' '{print $7}')

if [ ! -z $verbose ]; then verbose_="&verbose=$verbose"; fi
if [ ! -z $recursive ]; then recursive_="&recursive=$recursive"; fi

curl -k -X POST "https://10.0.0.229:5001/api/v0/routing/provide?arg=$arg$verbose_$recursive_"

# arg [string]: The key[s] to send provide records for. Required: yes.
# verbose [bool]: Print extra information. Required: no.
# recursive [bool]: Recursively provide entire graph. Required: no.
