#!/bin/bash
echo "Content-type: application/json"
echo

curl -X POST "http://10.0.0.229:5001/api/v0/bootstrap"

# This endpoint takes no arguments.

# RENAMED bootstrap->boot_strap because there's also /api/v0/bootstrap/add
