#!/bin/bash
echo "Content-type: application/json"
echo; url="$REQUEST_URI"

eval $(echo "$url" | awk -F'[=&?]' '{print $2}')=$(echo "$url" | awk -F'[=&?]' '{print $3}')
eval $(echo "$url" | awk -F'[=&?]' '{print $4}')=$(echo "$url" | awk -F'[=&?]' '{print $5}')
eval $(echo "$url" | awk -F'[=&?]' '{print $6}')=$(echo "$url" | awk -F'[=&?]' '{print $7}')
eval $(echo "$url" | awk -F'[=&?]' '{print $8}')=$(echo "$url" | awk -F'[=&?]' '{print $9}')

curl -X POST "http://10.0.0.229:5001/api/v0/cat?arg=$arg&offset=$offset&length=$length&progress=$progress"

# arg [string]: The path to the IPFS object(s) to be outputted. Required: yes.
# offset [int64]: Byte offset to begin reading from. Required: no.                                                  
# length [int64]: Maximum number of bytes to read. Required: no.                                                    
# progress [bool]: Stream progress data. Default: true. Required: no.
